# The hand-written half of the Fantastic Four shelf. Same shape as
# omnibus_meta.py and hulk_meta.py -- ORDER (wiki-backed), PLACEHOLDERS (tiles
# with no contents), SHELF (display order by id), PLACEHOLDER_PAGES, and
# SERIES_EXTRA for the series the shared SERIES table in build_omnibus_data.py
# does not already carry.
#
# Scope: the Fantastic Four's own books, plus the two family volumes the user
# asked for by name -- the Thing's solo omnibus and Doctor Doom's Book of Doom.
# Deliberately off the shelf: Marvel Two-In-One (the Thing's team-up book, the
# same call that dropped Marvel Team-Up from the Spider-Man shelf), Fantastic
# Four/Doom 2099, Heroes Reborn, and the Silver Surfer omnibuses.
#
# `chapterby` overrides the automatic chaptering heuristic for one volume.

ORDER = [
("Fantastic Four Omnibus Vol 1 1", dict(id="ff-o1", title="Fantastic Four Omnibus", vol="Vol. 1",
  creators="Stan Lee & Jack Kirby", era="1961–1964", released="Jan 2005",
  art="o-kirby", tex="tex-krackle", spine="Fantastic Four",
 cover="Art/Fantastic-Four/ff-o1.jpg",
  note="Where the Marvel Universe starts. Thirty issues and the first annual, inventing the Skrulls, Doctor Doom, the Puppet Master and Namor's return one month at a time.")),
("Fantastic Four Omnibus Vol 1 2", dict(id="ff-o2", title="Fantastic Four Omnibus", vol="Vol. 2",
  creators="Stan Lee & Jack Kirby", era="1964–1967", released="Jun 2007",
  art="o-kirby", tex="tex-cosmic", spine="Fantastic Four",
 cover="Art/Fantastic-Four/ff-o2.jpg",
  note="The imperial run: the Frightful Four, the Inhumans, Wyatt Wingfoot — and #48–50, the Galactus Trilogy, which is where the book stops being a superhero comic and starts being cosmic.")),
("Fantastic Four Omnibus Vol 1 3", dict(id="ff-o3", title="Fantastic Four Omnibus", vol="Vol. 3",
  creators="Stan Lee & Jack Kirby", era="1967–1970", released="Apr 2015",
  art="o-kirby", tex="tex-negzone", spine="Fantastic Four",
 cover="Art/Fantastic-Four/ff-o3.jpg",
  note="The end of Lee and Kirby together. The Black Panther's debut, Annihilus and the Negative Zone, the Kree Sentry, and Franklin Richards born.")),
("Fantastic Four Omnibus Vol 1 4", dict(id="ff-o4", title="Fantastic Four Omnibus", vol="Vol. 4",
  creators="Stan Lee, John Buscema & John Romita Sr.", era="1969–1972", released="Aug 2021",
  art="o-bronze", tex="tex-halftone", spine="Fantastic Four",
 cover="Art/Fantastic-Four/ff-o4.jpg",
  note="After Kirby. Lee writes on with Buscema and Romita — Agatha Harkness, the Overmind, Annihilus again — and the book closes with The Lost Adventure, the Kirby story Marvel did not print until 2008. It reprints #91–93 from Vol. 3, so those three share their ids across both volumes.")),
("Fantastic Four Omnibus Vol 1 5", dict(id="ff-o5", title="Fantastic Four Omnibus", vol="Vol. 5",
  creators="Roy Thomas, Gerry Conway & John Buscema", era="1972–1975", released="Nov 2024",
  art="o-bronze", tex="tex-krackle", spine="Fantastic Four",
 cover="Art/Fantastic-Four/ff-o5.jpg",
  note="Thomas and Conway hold the line: Thundra, Quicksilver and Crystal's wedding, and Reed shutting down his own son's mind — the decision the next twenty years keep coming back to.")),
("Fantastic Four Omnibus Vol 1 6", dict(id="ff-o6", title="Fantastic Four Omnibus", vol="Vol. 6",
  creators="Roy Thomas, Len Wein, Marv Wolfman & George Pérez", era="1975–1978", released="Jun 2025",
  art="o-perez", tex="tex-cosmic", spine="Fantastic Four",
 cover="Art/Fantastic-Four/ff-o6.jpg",
  note="Pérez arrives on the book that made him, and the Impossible Man, Galactus and the Brute run through it. Closes with the What If? that asks what the Marvel Bullpen would have done with the powers.")),
("Fantastic Four by John Byrne Omnibus Vol 1 1", dict(id="byrne-o1", title="Fantastic Four by John Byrne Omnibus", vol="Vol. 1",
  creators="John Byrne", era="1977–1983", released="Nov 2011",
  art="o-byrne", tex="tex-cosmic", spine="By John Byrne",
 cover="Art/Fantastic-Four/byrne-o1.jpg",
  note="Writing and drawing both, Byrne makes this the best-regarded run since Kirby. Opens with the Marvel Team-Ups he drew first, then FF #232 onward — Doom, the Negative Zone, and Sue finally written as the most powerful one in the room.")),
("Fantastic Four by John Byrne Omnibus Vol 1 2", dict(id="byrne-o2", title="Fantastic Four by John Byrne Omnibus", vol="Vol. 2",
  creators="John Byrne", era="1984–1986", released="Dec 2013",
  art="o-byrne", tex="tex-negzone", spine="By John Byrne",
 cover="Art/Fantastic-Four/byrne-o2.jpg",
  note="Secret Wars breaks the team up: the Thing stays behind on Battleworld, She-Hulk takes his chair, and Doom comes back remade. Runs to where Byrne walked off the book.")),
("Fantastic Four by Waid & Wieringo Omnibus Vol 1 1", dict(id="waid-o1", title="Fantastic Four by Waid & Wieringo Omnibus", vol="",
  creators="Mark Waid & Mike Wieringo", era="2002–2005", released="Dec 2018",
  art="o-waid", tex="tex-krackle", spine="Waid & Wieringo",
 cover="Art/Fantastic-Four/waid-o1.jpg",
  note="Note the jump — Fantastic Four #296–488 has never been collected in omnibus, so sixteen years pass between this book and Byrne's last one. Waid and Wieringo restart from first principles, and Unthinkable is the best Doom story in decades.")),
("Fantastic Four by Millar & Hitch Omnibus Vol 1 1", dict(id="millar-o1", title="Fantastic Four by Millar & Hitch Omnibus", vol="",
  creators="Mark Millar & Bryan Hitch", era="2008–2009", released="Apr 2023",
  art="o-millar", tex="tex-cosmic", spine="Millar & Hitch",
 cover="Art/Fantastic-Four/millar-o1.jpg",
  note="Widescreen and loud: the Marquis of Death, Doom's origin retold, Ben's wedding, and Marvel 1985 collected alongside as the odd one out.")),
("Fantastic Four by Jonathan Hickman Omnibus Vol 1 1", dict(id="hick-o1", title="Fantastic Four by Jonathan Hickman Omnibus", vol="Vol. 1",
  creators="Jonathan Hickman, Dale Eaglesham & Steve Epting", era="2009–2011", released="Oct 2013",
  art="o-hickman", tex="tex-negzone", spine="By Hickman",
 cover="Art/Fantastic-Four/hick-o1.jpg",
  note="The long game. The Council of Reeds, the Future Foundation, the War of Four Cities being set up years before it lands — and the death that turns Fantastic Four into FF.")),
("Fantastic Four by Jonathan Hickman Omnibus Vol 1 2", dict(id="hick-o2", title="Fantastic Four by Jonathan Hickman Omnibus", vol="Vol. 2",
  creators="Jonathan Hickman, Steve Epting & Barry Kitson", era="2011–2012", released="Nov 2014",
  art="o-hickman", tex="tex-cosmic", spine="By Hickman",
 cover="Art/Fantastic-Four/hick-o2.jpg",
  note="Both books at once — FF and the restored Fantastic Four, month by month — through to #611, where every thread planted in Vol. 1 is paid off at the same time.")),
("Fantastic Four by Matt Fraction Omnibus Vol 1 1", dict(id="frac-o1", title="Fantastic Four by Matt Fraction Omnibus", vol="",
  creators="Matt Fraction, Mark Bagley & Michael Allred", era="2012–2013", released="Feb 2015",
  art="o-fraction", tex="tex-krackle", spine="By Fraction",
 cover="Art/Fantastic-Four/frac-o1.jpg",
  note="A family road trip through space and time, while a substitute team minds the Baxter Building and Allred draws them. Both Marvel NOW! series in one book.")),
("Fantastic Four by Dan Slott Omnibus Vol 1 1", dict(id="slott-o1", title="Fantastic Four by Dan Slott Omnibus", vol="Vol. 1",
  creators="Dan Slott, Sara Pichelli & Aaron Kuder", era="2018–2020", released="Jul 2026",
  art="o-slott", tex="tex-cosmic", chapterby="series", spine="By Dan Slott",
 cover="Art/Fantastic-Four/slott-o1.jpg",
  note="The family comes home after Secret Wars. Ben and Alicia's wedding, the Griever at the End of All Things, and Doom written as the most dangerous man alive again.")),
("Fantastic Four by Dan Slott Omnibus Vol 1 2", dict(id="slott-o2", title="Fantastic Four by Dan Slott Omnibus", vol="Vol. 2",
  creators="Dan Slott, R.B. Silva & Rachael Stott", era="2020–2022", released="Announced",
  art="o-slott", tex="tex-negzone", spine="By Dan Slott",
 cover="Art/Fantastic-Four/slott-o2.jpg",
  note="The back half of the run, ending in the Reckoning War. Solicited for December 2026.")),
("Thing Omnibus Vol 1 1", dict(id="thing-o1", title="Thing Omnibus", vol="",
  creators="John Byrne, Mike Carlin & Ron Wilson", era="1983–1991", released="Dec 2022",
  art="o-thing", tex="tex-halftone", spine="The Thing",
 cover="Art/Fantastic-Four/thing-o1.jpg",
  note="Ben Grimm on his own, spun out of Byrne's run and meant to be read alongside it — which is why it sits between the two Byrne volumes here. Its first two issues are in Byrne Vol. 1 as well, and share their ids.")),
("Doctor Doom: The Book of Doom Omnibus Vol 1 1", dict(id="doom-o1", title="Doctor Doom: The Book of Doom Omnibus", vol="",
  creators="Stan Lee, Jack Kirby, Roy Thomas & Wally Wood", era="1962–1977", released="Aug 2022",
  art="o-doom", tex="tex-halftone", chapterby="series", spine="Book of Doom",
 cover="Art/Fantastic-Four/doom-o1.jpg",
  note="Latveria's side of the story, gathered across fifteen years and a dozen titles, so it doubles back over the Lee/Kirby volumes and shares their ids. Astonishing Tales and Super-Villain Team-Up are the parts hardest to find anywhere else.")),
("Ultimate Fantastic Four Omnibus Vol 1 1", dict(id="uff-o1", title="Ultimate Fantastic Four Omnibus", vol="Vol. 1",
  creators="Brian Michael Bendis, Mark Millar & Adam Kubert", era="2004–2006", released="Mar 2025",
  art="o-ultimate", tex="tex-negzone", spine="Ultimate FF",
 cover="Art/Fantastic-Four/uff-o1.jpg",
  note="A separate universe and a younger team — the accident is a teleporter, not a rocket, and Reed is a prodigy the government keeps in a building with the others. Marvel Zombies starts here.")),
("Ultimate Fantastic Four Omnibus Vol 1 2", dict(id="uff-o2", title="Ultimate Fantastic Four Omnibus", vol="Vol. 2",
  creators="Mike Carey, Mark Millar & Pasqual Ferry", era="2006–2009", released="Apr 2026",
  art="o-ultimate", tex="tex-cosmic", spine="Ultimate FF",
 cover="Art/Fantastic-Four/uff-o2.jpg",
  note="Ultimate Doom, the back half of Ultimate Extinction, and the crossovers that close the line out before Ultimatum ends it.")),
]

# Nothing pending on this shelf.
PLACEHOLDERS = []

# Display order of the shelf, by id. A reading order, not publication order:
# the Thing's solo book sits between the two Byrne volumes because that is
# where it was published and where it reads, and the two cross-era anthologies
# (Doom, Ultimate) sit at the end rather than interrupting the main line.
SHELF = [
  "ff-o1", "ff-o2", "ff-o3", "ff-o4", "ff-o5", "ff-o6",
  "byrne-o1", "thing-o1", "byrne-o2",
  "waid-o1", "millar-o1",
  "hick-o1", "hick-o2", "frac-o1",
  "slott-o1", "slott-o2",
  "doom-o1",
  "uff-o1", "uff-o2",
]

PLACEHOLDER_PAGES = {}

# Series these books collect that the shared SERIES table does not carry.
# Volume-2-and-later series carry their launch year the way the shared table
# already does for Amazing Spider-Man (1999); plain Vol 1 runs do not need one.
# `ff3` and `av` are reused from the Hulk shelf's table on purpose -- the
# marvel.com id store is shared, so the same series must key the same way.
SERIES_EXTRA = {
 "Fantastic Four Vol 3":                               ("ff3",    "Fantastic Four (1998)"),
 "Fantastic Four Vol 4":                               ("ff4",    "Fantastic Four (2012)"),
 "Fantastic Four Vol 6":                               ("ff6",    "Fantastic Four (2018)"),
 "Fantastic Four Annual Vol 2":                        ("ff3ann", "Fantastic Four Annual (1998)"),
 "FF Vol 1":                                           ("ff11",   "FF (2011)"),
 "FF Vol 2":                                           ("ff12",   "FF (2012)"),
 "Fantastic Four Special Vol 1":                       ("ffsp",   "Fantastic Four Special"),
 "Fantastic Four Special Edition Vol 1":               ("ffse",   "Fantastic Four Special Edition"),
 "Fantastic Four Roast Vol 1":                         ("ffrst",  "Fantastic Four Roast"),
 "Fantastic Four: The Lost Adventure Vol 1":           ("ffla",   "Fantastic Four: The Lost Adventure"),
 "Fantastic Four: Wedding Special Vol 1":              ("ffws",   "Fantastic Four: Wedding Special"),
 "Fantastic Four: Road Trip Vol 1":                    ("ffrt",   "Fantastic Four: Road Trip"),
 "Fantastic Four: Negative Zone Vol 1":                ("ffnz",   "Fantastic Four: Negative Zone"),
 "Fantastic Four: Grimm Noir Vol 1":                   ("ffgn",   "Fantastic Four: Grimm Noir"),
 "Fantastic Four: 4 Yancy Street Vol 1":               ("ffys",   "Fantastic Four: 4 Yancy Street"),
 "Fantastic Four: Reckoning War Alpha Vol 1":          ("ffrwa",  "Fantastic Four: Reckoning War Alpha"),
 "Reckoning War: Trial of the Watcher Vol 1":          ("rwtw",   "Reckoning War: Trial of the Watcher"),
 "Empyre: Fantastic Four Vol 1":                       ("empff",  "Empyre: Fantastic Four"),
 "Empyre: Fallout Fantastic Four Vol 1":               ("empfo",  "Empyre: Fallout Fantastic Four"),
 "Giant-Size Fantastic Four Vol 1":                    ("gsff",   "Giant-Size Fantastic Four"),
 "Giant-Size Super-Stars Vol 1":                       ("gsss",   "Giant-Size Super-Stars"),
 "Fantastic Force Vol 2":                              ("ffor",   "Fantastic Force (2009)"),
 "Dark Reign: Fantastic Four Vol 1":                   ("drff",   "Dark Reign: Fantastic Four"),
 "Dark Reign: The Cabal Vol 1":                        ("drcab",  "Dark Reign: The Cabal"),
 "Marvel NOW! Point One Vol 1":                        ("mnpo",   "Marvel NOW! Point One"),
 "Marvel 1985 Vol 1":                                  ("m1985",  "Marvel 1985"),
 "Thing Vol 1":                                        ("thing",  "The Thing"),
 "Marvel Two-In-One Annual Vol 1":                     ("mtioann","Marvel Two-In-One Annual"),
 "Questprobe Vol 1":                                   ("qprobe", "Questprobe"),
 "Marvel Fanfare Vol 1":                               ("mfan",   "Marvel Fanfare"),
 "Marvel Super-Heroes Vol 2":                          ("msh2",   "Marvel Super-Heroes (1990)"),
 "Marvel Graphic Novel Vol 1":                         ("mgn",    "Marvel Graphic Novel"),
 "Marvel Double Shot Vol 1":                           ("mdshot", "Marvel Double Shot"),
 "Marvel Super Heroes Secret Wars Vol 1":              ("swars",  "Secret Wars"),
 "Secret Wars II Vol 1":                               ("swars2", "Secret Wars II"),
 "Astonishing Tales Vol 1":                            ("astt",   "Astonishing Tales"),
 "Super-Villain Team-Up Vol 1":                        ("svtu",   "Super-Villain Team-Up"),
 "Giant-Size Super-Villain Team-Up Vol 1":             ("gssvtu", "Giant-Size Super-Villain Team-Up"),
 "Books of Doom Vol 1":                                ("bodoom", "Books of Doom"),
 "FOOM Vol 1":                                         ("foom",   "FOOM"),
 "Epic Illustrated Vol 1":                             ("epic",   "Epic Illustrated"),
 "What The--?! Vol 1":                                 ("wthe",   "What The--?!"),
 "Champions Vol 1":                                    ("champ",  "Champions"),
 "Alpha Flight Vol 1":                                 ("alf",    "Alpha Flight"),
 "Avengers Vol 1":                                     ("av",     "Avengers"),
 "Avengers Annual Vol 1":                              ("avann",  "Avengers Annual"),
 "West Coast Avengers Vol 2":                          ("wca",    "West Coast Avengers"),
 "Iron Man Vol 1":                                     ("im",     "Iron Man"),
 "Uncanny X-Men Vol 1":                                ("uxm",    "Uncanny X-Men"),
 "Ultimate Fantastic Four Vol 1":                      ("uff",    "Ultimate Fantastic Four"),
 "Ultimate Fantastic Four Annual Vol 1":               ("uffann", "Ultimate Fantastic Four Annual"),
 "Ultimate Fantastic Four/X-Men Vol 1":                ("uffxm",  "Ultimate Fantastic Four/X-Men"),
 "Ultimate X-Men/Fantastic Four Vol 1":                ("uxmff",  "Ultimate X-Men/Fantastic Four"),
 "Ultimate Fantastic Four/Ultimate X-Men Annual Vol 1":("uffuxa", "Ultimate FF/Ultimate X-Men Annual"),
 "Ultimate X-Men/Ultimate Fantastic Four Annual Vol 1":("uxmufa", "Ultimate X-Men/Ultimate FF Annual"),
 "Ultimatum: Fantastic Four Requiem Vol 1":            ("ultffr", "Ultimatum: Fantastic Four Requiem"),
}
