# The hand-written half of the Hulk shelf. Same shape as omnibus_meta.py --
# ORDER (wiki-backed), PLACEHOLDERS (tiles with no contents), SHELF (display
# order by id), PLACEHOLDER_PAGES, and SERIES_EXTRA for the series the shared
# SERIES table in build_omnibus_data.py does not already carry.
#
# Scope: mainline Bruce Banner only. She-Hulk's four omnibuses are a different
# character and are deliberately off the shelf, as are books where the Hulk is
# a guest rather than the subject.
#
# `chapterby` overrides the automatic chaptering heuristic for one volume.
# Left off, gen() picks per-series or "Part N" by average run length; the Hulk
# books that trip the "Part N" branch are anthologies and crossovers whose
# tie-in minis read better as their own chapters, so they ask for "series".

ORDER = [
("Incredible Hulk Omnibus Vol 1 1", dict(id="inc-o1", title="Incredible Hulk Omnibus", vol="Vol. 1",
  creators="Stan Lee, Jack Kirby & Steve Ditko", era="1962–1968", released="Jun 2008",
  art="o-kirby", tex="tex-gamma", spine="Incredible Hulk",
 cover="Art/Hulk/inc-o1.jpg",
  note="Where it starts. Six issues of the cancelled 1962 series, the whole Tales to Astonish run, and Hulk #102 picking the numbering back up.")),
("Incredible Hulk Omnibus Vol 1 2", dict(id="inc-o2", title="Incredible Hulk Omnibus", vol="Vol. 2",
  creators="Stan Lee, Roy Thomas & Herb Trimpe", era="1968–1970", released="Nov 2023",
  art="o-trimpe", tex="tex-smash", spine="Incredible Hulk",
 cover="Art/Hulk/inc-o2.jpg",
  note="Trimpe becomes the definitive Bronze Age Hulk artist. Ka-Zar, the Rhino, the Leader's Humanoids and the first Sasquatch.")),
("Incredible Hulk Omnibus Vol 1 3", dict(id="inc-o3", title="Incredible Hulk Omnibus", vol="Vol. 3",
  creators="Roy Thomas, Archie Goodwin & Herb Trimpe", era="1971–1973", released="Nov 2025",
  art="o-buscema", tex="tex-gamma", spine="Incredible Hulk",
 cover="Art/Hulk/inc-o3.jpg",
  note="Jarella, the Harpy, Doc Samson's debut and the Avengers #88 crossover that leads straight into Hulk #140.")),
("Incredible Hulk Omnibus Vol 1 4", dict(id="inc-o4", title="Incredible Hulk Omnibus", vol="Vol. 4",
  creators="Len Wein, Roger Stern & Herb Trimpe", era="1974–1977", released="Announced",
  art="o-bronze", tex="tex-smash", spine="Incredible Hulk",
 cover="Art/Hulk/inc-o4.jpg",
  note="Hulk #180–181: the first Wolverine. Also the Bi-Beast, the Abomination's return, and issue #200. Solicited for February 2027.")),
("Incredible Hulk by Peter David Omnibus Vol 1 1", dict(id="pad-o1", title="Incredible Hulk by Peter David Omnibus", vol="Vol. 1",
  creators="Peter David, Todd McFarlane & Jeff Purves", era="1987–1990", released="Jan 2020",
  art="o-pad", tex="tex-halftone", spine="By Peter David",
 cover="Art/Hulk/pad-o1.jpg",
  note="The grey Hulk as Las Vegas leg-breaker Joe Fixit. Note the jump: Hulk #210–327 has never been collected in omnibus, so this opens 118 issues after Vol. 4 closes.")),
("Incredible Hulk by Peter David Omnibus Vol 1 2", dict(id="pad-o2", title="Incredible Hulk by Peter David Omnibus", vol="Vol. 2",
  creators="Peter David, Dale Keown & Jeff Purves", era="1990–1992", released="Oct 2020",
  art="o-pad", tex="tex-smash", spine="By Peter David",
 cover="Art/Hulk/pad-o2.jpg",
  note="Keown arrives and the Hulk is merged into the Professor. Ground Zero, the Pantheon, and issue #400.")),
("Incredible Hulk by Peter David Omnibus Vol 1 3", dict(id="pad-o3", title="Incredible Hulk by Peter David Omnibus", vol="Vol. 3",
  creators="Peter David, Gary Frank & George Pérez", era="1993–1995", released="Jun 2021",
  art="o-pad", tex="tex-gamma", spine="By Peter David",
 cover="Art/Hulk/pad-o3.jpg",
  note="Future Imperfect — the Maestro — plus the Troyjan War and Betty and Bruce finally married.")),
("Incredible Hulk by Peter David Omnibus Vol 1 4", dict(id="pad-o4", title="Incredible Hulk by Peter David Omnibus", vol="Vol. 4",
  creators="Peter David, Angel Medina & Adam Kubert", era="1995–1997", released="May 2022",
  art="o-pad", tex="tex-halftone", spine="By Peter David",
 cover="Art/Hulk/pad-o4.jpg",
  note="The end of the twelve-year run: Onslaught, the Hulk split in two, and Banner alone.")),
("Hulk: Maestro by Peter David Omnibus Vol 1 1", dict(id="maestro-o1", title="Hulk: Maestro by Peter David Omnibus", vol="",
  creators="Peter David, George Pérez & Germán Peralta", era="1992–2022", released="Sep 2023",
  art="o-maestro", tex="tex-gamma", chapterby="series", spine="Maestro",
 cover="Art/Hulk/maestro-o1.jpg",
  note="Every Maestro story in one book, so it doubles back over Future Imperfect and Hulk #460–461 from the volumes above — those issues share their ids, so marking them here marks them there.")),
("Incredible Hulk by Byrne & Casey Omnibus Vol 1 1", dict(id="byrne-o1", title="Incredible Hulk by Byrne & Casey Omnibus", vol="",
  creators="John Byrne, Joe Casey & Ron Garney", era="1998–2000", released="May 2024",
  art="o-byrne", tex="tex-smash", spine="Byrne & Casey",
 cover="Art/Hulk/byrne-o1.jpg",
  note="The post-David relaunch: Byrne's short run, the retitled Hulk #1–11, and Rampaging Hulk.")),
("Incredible Hulk: Return of the Monster Omnibus Vol 1 1", dict(id="rotm-o1", title="Incredible Hulk: Return of the Monster Omnibus", vol="",
  creators="Bruce Jones, John Romita Jr. & Lee Weeks", era="2001–2004", released="Jun 2026",
  art="o-jones", tex="tex-halftone", spine="Return of the Monster",
 cover="Art/Hulk/rotm-o1.jpg",
  note="Banner on the run, hunted by a conspiracy called Home Base. A thriller more than a superhero book, and the whole Bruce Jones run in one volume.")),
("Incredible Hulk by Peter David Omnibus Vol 1 5", dict(id="pad-o5", title="Incredible Hulk by Peter David Omnibus", vol="Vol. 5",
  creators="Peter David, Lee Weeks & Jae Lee", era="2002–2021", released="May 2022",
  art="o-pad", tex="tex-burst", chapterby="series", spine="By Peter David",
 cover="Art/Hulk/pad-o5.jpg",
  note="David's returns to the character, gathered rather than serialised: The End, the Tempest Fugit arc that follows Return of the Monster, and a long tail of one-shots.")),
("Hulk: Planet Hulk Omnibus Vol 1 1", dict(id="planet-o1", title="Hulk: Planet Hulk Omnibus", vol="",
  creators="Greg Pak & Carlo Pagulayan", era="2006–2007", released="Sep 2017",
  art="o-planet", tex="tex-burst", chapterby="series", spine="Planet Hulk",
 cover="Art/Hulk/planet-o1.jpg",
  note="The Illuminati fire him into space and he lands on Sakaar. Gladiator, then king. The best-regarded Hulk story of the century so far.")),
("Hulk: World War Hulk Omnibus Vol 1 1", dict(id="wwh-o1", title="Hulk: World War Hulk Omnibus", vol="",
  creators="Greg Pak & John Romita Jr.", era="2007–2008", released="Oct 2017",
  art="o-warbound", tex="tex-burst", chapterby="series", spine="World War Hulk",
 cover="Art/Hulk/wwh-o1.jpg",
  note="He comes back for the Illuminati. The core series plus every tie-in and the whole Aftersmash line, each mini as its own chapter.")),
("Hulk by Loeb & McGuinness Omnibus Vol 1 1", dict(id="loeb-o1", title="Hulk by Loeb & McGuinness Omnibus", vol="",
  creators="Jeph Loeb & Ed McGuinness", era="2008–2010", released="Jun 2019",
  art="o-redhulk", tex="tex-smash", spine="Loeb & McGuinness",
 cover="Art/Hulk/loeb-o1.jpg",
  note="The Red Hulk mystery and the Hulk (2008) ongoing. Loud, and the whodunit is the point.")),
("Immortal Hulk Omnibus Vol 1 1", dict(id="imm-o1", title="Immortal Hulk Omnibus", vol="",
  creators="Al Ewing & Joe Bennett", era="2018–2021", released="Aug 2023",
  art="o-immortal", tex="tex-gamma", spine="Immortal Hulk",
 cover="Art/Hulk/imm-o1.jpg",
  note="All 50 issues plus #0 and the tie-ins. A horror book about what the Hulk actually is — the run that reframed the character.")),
("Hulk by Cates & Ottley Omnibus Vol 1 1", dict(id="cates-o1", title="Hulk by Cates & Ottley Omnibus", vol="",
  creators="Donny Cates & Ryan Ottley", era="2021–2022", released="Nov 2024",
  art="o-cates", tex="tex-smash", chapterby="series", spine="Cates & Ottley",
 cover="Art/Hulk/cates-o1.jpg",
  note="Banner pilots the Hulk like a ship. Runs straight into Banner of War, which is why the two Thor issues sit between Hulk #6 and #8.")),
]

# Nothing pending on this shelf yet.
PLACEHOLDERS = []

# Display order of the shelf, by id. Curated reading order, so Maestro sits with
# the Peter David run it belongs to and pad-o5 sits after Return of the Monster,
# where its Incredible Hulk (2000) #77–87 actually continues from.
SHELF = [
  "inc-o1", "inc-o2", "inc-o3", "inc-o4",
  "pad-o1", "pad-o2", "pad-o3", "pad-o4", "maestro-o1",
  "byrne-o1", "rotm-o1", "pad-o5",
  "planet-o1", "wwh-o1", "loeb-o1",
  "imm-o1", "cates-o1",
]

PLACEHOLDER_PAGES = {}

# Series these books collect that the shared SERIES table does not carry.
# Incredible Hulk Vol 1, Fantastic Four Vol 1, Web of Spider-Man Vol 1, Marvel
# Comics Presents, Marvel Super-Heroes and Marvel Treasury Edition are already
# in it and are deliberately absent here.
SERIES_EXTRA = {
 "Tales to Astonish Vol 1":                            ("tta",    "Tales to Astonish"),
 "Tales to Astonish Vol 3":                            ("tta3",   "Tales to Astonish (1994)"),
 "Incredible Hulk Vol 2":                              ("hulk2",  "Incredible Hulk (2000)"),
 "Incredible Hulk Vol 3":                              ("hulk3",  "Incredible Hulk (2009)"),
 "Hulk Vol 1":                                         ("hk99",   "Hulk (1999)"),
 "Hulk Vol 2":                                         ("hulk08", "Hulk (2008)"),
 "Hulk Vol 5":                                         ("hulk21", "Hulk (2021)"),
 "Incredible Hulk Annual Vol 1":                       ("hkann",  "Incredible Hulk Annual"),
 "Incredible Hulk King Size Special Vol 1":            ("hkss",   "Incredible Hulk King-Size Special"),
 "Hulk Annual Vol 1":                                  ("hk99ann","Hulk Annual"),
 "Hulk/Sub-Mariner Annual Vol 1":                      ("hksmann","Hulk/Sub-Mariner Annual"),
 "X-Man/Incredible Hulk Annual Vol 1":                 ("xmhkann","X-Man/Incredible Hulk Annual"),
 "Rampaging Hulk Vol 2":                               ("rhulk",  "Rampaging Hulk (1998)"),
 "Giant-Size Hulk Vol 2":                              ("gshulk", "Giant-Size Hulk"),
 "King-Size Hulk Vol 1":                               ("kshulk", "King-Size Hulk"),
 "Hulk Monster-Size Special Vol 1":                    ("hkmss",  "Hulk Monster-Size Special"),
 "Incredible Hulk Ashcan Edition Vol 1":               ("hkash",  "Incredible Hulk Ashcan"),
 "Savage Hulk Vol 1":                                  ("svh",    "Savage Hulk"),
 "Marvel Adventures Hulk Vol 1":                       ("mahulk", "Marvel Adventures Hulk"),
 "Hulk-Sized Mini Hulks Vol 1":                        ("hsmh",   "Hulk-Sized Mini Hulks"),
 "Incredible Hulk vs. Venom Vol 1":                    ("hkven",  "Incredible Hulk vs. Venom"),
 "Hulk vs. Fin Fang Foom Vol 1":                       ("hkfff",  "Hulk vs. Fin Fang Foom"),
 "Hulk/Wolverine: 6 Hours Vol 1":                      ("hkwolv", "Hulk/Wolverine: 6 Hours"),
 "Hulk & Thing: Hard Knocks Vol 1":                    ("hkthing","Hulk & Thing: Hard Knocks"),
 "Hulk: Destruction Vol 1":                            ("hkdes",  "Hulk: Destruction"),
 "Hulk: Broken Worlds Vol 1":                          ("hkbw",   "Hulk: Broken Worlds"),
 "Hulk: Future Imperfect Vol 1":                       ("hkfi",   "Hulk: Future Imperfect"),
 "Future Imperfect Vol 1":                             ("fimp",   "Future Imperfect (2015)"),
 "Maestro Vol 1":                                      ("mae",    "Maestro"),
 "Maestro: War and Pax Vol 1":                         ("maewp",  "Maestro: War and Pax"),
 "Maestro: World War M Vol 1":                         ("maewwm", "Maestro: World War M"),
 "Abominations Vol 1":                                 ("abom",   "Abominations"),
 "Incredible Hulk: Hercules Unleashed Vol 1":          ("hkherc", "Hulk: Hercules Unleashed"),
 "Incredible Hulk: The End Vol 1":                     ("hkend",  "Hulk: The End"),
 "Incredible Hulk: Last Call Vol 1":                   ("hklc",   "Hulk: Last Call"),
 "What If General Ross Had Become the Hulk? Vol 1":    ("wiross", "What If? General Ross"),
 "What If? Planet Hulk Vol 1":                         ("wiph",   "What If? Planet Hulk"),
 "Planet Hulk: Gladiator Guidebook Vol 1":             ("phgg",   "Planet Hulk: Gladiator Guidebook"),
 "World War Hulk Vol 1":                               ("wwh",    "World War Hulk"),
 "World War Hulk Prologue: World Breaker Vol 1":       ("wwhwb",  "WWH Prologue: World Breaker"),
 "World War Hulk: X-Men Vol 1":                        ("wwhxm",  "World War Hulk: X-Men"),
 "World War Hulk: Gamma Corps Vol 1":                  ("wwhgc",  "World War Hulk: Gamma Corps"),
 "World War Hulk: Front Line Vol 1":                   ("wwhfl",  "World War Hulk: Front Line"),
 "World War Hulk: Aftersmash Vol 1":                   ("wwhas",  "World War Hulk: Aftersmash"),
 "World War Hulk Aftersmash: Damage Control Vol 1":    ("wwhdc",  "Aftersmash: Damage Control"),
 "World War Hulk Aftersmash: Warbound Vol 1":          ("wwhwar", "Aftersmash: Warbound"),
 "Marvel Spotlight: World War Hulk Vol 1":             ("mspwwh", "Marvel Spotlight: World War Hulk"),
 "Fall of the Hulks: Gamma Vol 1":                     ("fothg",  "Fall of the Hulks: Gamma"),
 "Immortal Hulk Vol 1":                                ("imm",    "Immortal Hulk"),
 "Immortal Hulk: The Best Defense Vol 1":              ("immbd",  "Immortal Hulk: The Best Defense"),
 "Immortal Hulk: Time of Monsters Vol 1":              ("immtom", "Immortal Hulk: Time of Monsters"),
 "Immortal She-Hulk Vol 1":                            ("immsh",  "Immortal She-Hulk"),
 "Absolute Carnage: Immortal Hulk Vol 1":              ("acimm",  "Absolute Carnage: Immortal Hulk"),
 "King in Black: Immortal Hulk Vol 1":                 ("kibimm", "King in Black: Immortal Hulk"),
 "Defenders: The Best Defense Vol 1":                  ("defbd",  "Defenders: The Best Defense"),
 "Gamma Flight Vol 1":                                 ("gflt",   "Gamma Flight"),
 "Hulk vs. Thor: Banner of War Alpha Vol 1":           ("bowa",   "Hulk vs. Thor: Banner of War Alpha"),
 "Free Comic Book Day 2021: Avengers/Hulk Vol 1":      ("fcbd21", "FCBD 2021: Avengers/Hulk"),
 "Thor Vol 6":                                         ("thor6",  "Thor (2020)"),
 "Avengers Vol 1":                                     ("av",     "Avengers"),
 "Avengers Vol 7":                                     ("av7",    "Avengers (2016)"),
 "Avengers: The Initiative Vol 1":                     ("avin",   "Avengers: The Initiative"),
 "New Avengers: Illuminati Vol 1":                     ("nail",   "New Avengers: Illuminati"),
 "Invincible Iron Man Vol 1":                          ("iim",    "Invincible Iron Man"),
 "Irredeemable Ant-Man Vol 1":                         ("iam",    "Irredeemable Ant-Man"),
 "Heroes for Hire Vol 2":                              ("hfh2",   "Heroes for Hire (2006)"),
 "Ghost Rider Vol 6":                                  ("gr6",    "Ghost Rider (2006)"),
 "Punisher War Journal Vol 2":                         ("pwj2",   "Punisher War Journal (2007)"),
 "Wolverine Vol 3":                                    ("wolv3",  "Wolverine (2003)"),
 "Cable Vol 1":                                        ("cable",  "Cable"),
 "X-Factor Vol 1":                                     ("xfac",   "X-Factor"),
 "Fantastic Four Vol 3":                               ("ff3",    "Fantastic Four (1998)"),
 "New Fantastic Four Vol 1":                           ("nff",    "New Fantastic Four"),
 "Amazing Fantasy Vol 2":                              ("af2",    "Amazing Fantasy (2004)"),
 "Spider-Man 2099 Vol 2":                              ("sm2099", "Spider-Man 2099 (2014)"),
 "Symbiote Spider-Man: Crossroads Vol 1":              ("sssxr",  "Symbiote Spider-Man: Crossroads"),
 "Captain Marvel Vol 4":                               ("cm4",    "Captain Marvel (1999)"),
 "Exiles Vol 1":                                       ("exi",    "Exiles"),
 "Secret Wars: Battleworld Vol 1":                     ("swbw",   "Secret Wars: Battleworld"),
 "Onslaught: Marvel Universe Vol 1":                   ("onsmu",  "Onslaught: Marvel Universe"),
 "Heroes Reborn: The Return Vol 1":                    ("hrret",  "Heroes Reborn: The Return"),
 "Cutting Edge Vol 1":                                 ("cedge",  "Cutting Edge"),
 "Marvel Holiday Special Vol 1":                       ("mhs",    "Marvel Holiday Special"),
 "Marvel Comics Vol 1":                                ("mc1k",   "Marvel Comics"),
 "Breaking Into Comics the Marvel Way! Vol 1":         ("bicmw",  "Breaking Into Comics the Marvel Way!"),
}
